import type { Patient } from './types';

export const patients: Patient[] = [
  {
    id: 'user-123',
    name: 'Alex Johnson',
    age: 58,
    condition: 'Post-stroke hemiparesis',
    avatarUrl: 'https://picsum.photos/seed/alex/100/100',
    avatarHint: 'man smiling',
    lastSession: '2024-07-28',
    therapistNotes: 'Alex is showing steady improvement in fine motor control. Continue focusing on object manipulation exercises. Target grip strength increased to 25N.',
    totalHours: 42,
    avgGripStrength: 22,
    goalsCompleted: 5,
    targetStrength: 25,
    gripStrengthHistory: [
      { date: '2024-07-01', strength: 15 },
      { date: '2024-07-08', strength: 17 },
      { date: '2024-07-15', strength: 19 },
      { date: '2024-07-22', strength: 22 },
      { date: '2024-07-29', strength: 23 },
    ],
    therapyHoursHistory: [
        { date: 'Week 1', hours: 3.5 },
        { date: 'Week 2', hours: 4.0 },
        { date: 'Week 3', hours: 3.0 },
        { date: 'Week 4', hours: 4.5 },
        { date: 'Week 5', hours: 5.0 },
    ]
  },
  {
    id: 'user-456',
    name: 'Maria Garcia',
    age: 72,
    condition: 'Arthritis',
    avatarUrl: 'https://picsum.photos/seed/maria/100/100',
    avatarHint: 'woman portrait',
    lastSession: '2024-07-27',
    therapistNotes: 'Maria experiences joint stiffness in the morning. Begin sessions with gentle stretching exercises. Focus on maintaining current grip strength and reducing pain.',
    totalHours: 89,
    avgGripStrength: 15,
    goalsCompleted: 12,
    targetStrength: 15,
    gripStrengthHistory: [
      { date: '2024-07-01', strength: 16 },
      { date: '2024-07-08', strength: 15 },
      { date: '2024-07-15', strength: 15 },
      { date: '2024-07-22', strength: 14 },
      { date: '2024-07-29', strength: 15 },
    ],
    therapyHoursHistory: [
        { date: 'Week 1', hours: 2.5 },
        { date: 'Week 2', hours: 3.0 },
        { date: 'Week 3', hours: 2.0 },
        { date: 'Week 4', hours: 2.5 },
        { date: 'Week 5', hours: 2.0 },
    ]
  },
  {
    id: 'user-789',
    name: 'Chen Wei',
    age: 45,
    condition: 'Carpal tunnel syndrome recovery',
    avatarUrl: 'https://picsum.photos/seed/chen/100/100',
    avatarHint: 'asian man',
    lastSession: '2024-07-29',
    therapistNotes: 'Excellent progress post-surgery. Focus on endurance and sustained grip tasks. No signs of nerve compression reported.',
    totalHours: 25,
    avgGripStrength: 35,
    goalsCompleted: 4,
    targetStrength: 40,
    gripStrengthHistory: [
      { date: '2024-07-01', strength: 25 },
      { date: '2024-07-08', strength: 28 },
      { date: '2024-07-15', strength: 31 },
      { date: '2024-07-22', strength: 35 },
      { date: '2024-07-29', strength: 38 },
    ],
    therapyHoursHistory: [
        { date: 'Week 1', hours: 4.5 },
        { date: 'Week 2', hours: 5.0 },
        { date: 'Week 3', hours: 5.5 },
        { date: 'Week 4', hours: 6.0 },
        { date: 'Week 5', hours: 5.5 },
    ]
  },
];
